package moises.tokenizer;

public enum TokenType {
    NUMBER, NEWLINE, OPERATOR, EOF, UNKNOWN,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, LEFT_PAREN,
    RIGHT_PAREN, LESS, GREATER, EQUAL, NOTEQUAL,
    LESSEQUAL, GREATEREQUAL, ASSIGNMENT, NOT, OR, AND,
    KEYWORD, PRINT, PRINTLN, WAIT, END, SCRIPT, STRING,
    WHILE, IF, ELSE, PI, EULER, DEF, COMMA, LEFT_BRACKET, RIGHT_BRACKET
}